### ISSUE TITLE
Suggestions for Possible Learning Objectives

### ISSUE THREAD

**Issue by ghost** [MN-ASG/digi-curr#3]
Here are a few suggestions for learning objectives. These are just ideas to get us started. These might exist across a variety of classes, meaning I don't see all of these objectives tracking to a single course but rather with the curricula as a whole.
Students will be able to: 
- Describe the concept of Agile.
- Describe the concept of iterations and explain how iterations are used by an Agile project team.
- Use a version control repository to check in and check out files.
- Prepare for and participate in a stand-up meeting for an IT project.
- Critique code and produce feedback on the code for the author.
- Critique IT documentation and produce feedback on the documentation for the author.
- Engage in pair programming to develop a software application (or a web page, mobile app, etc.)

**Comment by CharlesTBetz** [comment]
Great suggestions - can you incorporate them into the wiki section as a
first draft?

**Comment by ghost** [comment]
Yes, I can definitely do that. Thanks.

Mary Lebens
Instructor, Information Technology
Anoka Technical College
1355 West Highway 10
Anoka, MN 55303
mlebens@anokatech.edu
763-576-4169

**Comment by CharlesTBetz** [comment]
Transferred to wiki https://github.com/MN-ASG/digi-curr/wiki/Learning-Objectives
