### ISSUE TITLE
'Next generation infrastructure' section

### ISSUE THREAD

**Issue by sgluhova** [MN-ASG/digi-curr#4]
Hello Everyone,

I have a few comments/questions on the 'Next generation infrastructure' section in the Reference-curricula document (below):
1. The last part of this section on 'How to take advantage of free cloud availability' mentions 'Concerns about lock-in'.  What does it mean?  Can it be rephrased?
2. The first section of the document talks about preparing students better for a world of Cloud-scale computing defined by “infrastructure as code.”  The way I understand it, the cloud environment and 'infrastructure as code' are two different concepts. For example, we can run servers in a cloud (say Azure).  'Infrastructure as code' refers to managing servers via text files which contain scripts written in Puppet, Chef or other software.  So the concept of 'infrastructure as code' applies to better management of servers with the use of text files (which minimizes human errors).  Cloud environment applies to running servers on remote servers.  Having said that, a cloud environment and  'infrastructure as code' are two separate concepts.  So should we rephrase this sentence to something like " students will gain skills to manage hardware and software in a cloud environment, apply 'infrastructure as code' concepts to administer nodes and learn concepts of virtualization.  I think we need to mention virtualization here as well.
3. •  Security hardening and antifragility are important practical topics.  Can we use a different word to define 'antifragility'?

Thank you!
Svetlana

**Comment by CharlesTBetz** [comment]
Great suggestions and critique - could you incorporate into the wiki? I
will assist.

**Comment by sgluhova** [comment]
Sure, I would like to do it if you show me how.  I am wrapping up now, I need to pick up my kids at 4 pm.  But if you send me instructions, I can do it tomorrow.  Thank you!

Svetlana Gluhova
Information Technology - Faculty
Hennepin Technical College
Email: Svetlana.Gluhova@hennepintech.edu

Brooklyn Park Campus               Eden Prairie Campus
9000 Brooklyn Blvd.                  13100 College View Drive
Brooklyn Park, MN  55445         Eden Prairie, MN  55347

  HennepinTech.eduhttps://mail.hennepintech.edu/owa/redir.aspx?SURL=9hxqIKAcynmf1C40r3rLvnrAz7PnouO_G2_TwvGvCbPIpzbLufzRCGgAdAB0AHAAOgAvAC8AdwB3AHcALgBoAGUAbgBuAGUAcABpAG4AdABlAGMAaAAuAGUAZAB1AC8A&URL=http%3a%2f%2fwww.hennepintech.edu%2f

**Comment by CharlesTBetz** [comment]
Have made some adaptions, please review

**Comment by sgluhova** [comment]
Changes look good!  

Thank you,
Svetlana Gluhova
